"""
Application constants
"""

# User Roles
ROLE_ADMIN = 'admin'
ROLE_MANAGER = 'manager'
ROLE_USER = 'user'

ALL_ROLES = [ROLE_ADMIN, ROLE_MANAGER, ROLE_USER]
ADMIN_ONLY = [ROLE_ADMIN]
ADMIN_MANAGER = [ROLE_ADMIN, ROLE_MANAGER]

# Task Status
STATUS_TODO = 'to_do'
STATUS_IN_PROGRESS = 'in_progress'
STATUS_FOR_REVIEW = 'for_review'
STATUS_DONE = 'done'

ALL_STATUSES = [STATUS_TODO, STATUS_IN_PROGRESS, STATUS_FOR_REVIEW, STATUS_DONE]

# Task Priority
PRIORITY_LOW = 'low'
PRIORITY_MEDIUM = 'medium'
PRIORITY_HIGH = 'high'

ALL_PRIORITIES = [PRIORITY_LOW, PRIORITY_MEDIUM, PRIORITY_HIGH]
